version: "3.8"

services:
  grafana:
    image: grafana/grafana:11.1.0
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - tempo
      - loki
      - mimir

  tempo:
    image: grafana/tempo:2.5.0
    command: ["-config.expand-env=true"]
    environment:
      - TEMPO_SERVER_HTTP_LISTEN_PORT=3200
      - TEMPO_OTLP_GRPC_LISTEN_ADDRESS=0.0.0.0:4317
    ports:
      - "3200:3200"
      - "4317:4317"

  loki:
    image: grafana/loki:3.0.0
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"

  mimir:
    image: grafana/mimir:2.12.0
    command: ["-config.expand-env=true", "-config.file=/etc/mimir/mimir.yml"]
    volumes:
      - ./mimir.yml:/etc/mimir/mimir.yml
    ports:
      - "9009:9009"
      - "9180:9180"

  alloy:
    image: grafana/alloy:latest
    command: ["--server.http.listen-addr=0.0.0.0:12345", "--stability.level=experimental", "--storage.path=/var/lib/alloy"]
    volumes:
      - ./alloy-config.alloy:/etc/alloy-config.alloy:ro
    ports:
      - "4319:4317"
      - "12345:12345"
    depends_on:
      - loki
      - mimir

  otelcol:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otelcol-config.yaml"]
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-config.yaml
    ports:
      - "4317:4317"   # gRPC
      - "4318:4318"   # HTTP
    depends_on:
      - loki
      - tempo