services:
  grafana:
    image: grafana/grafana:11.1.0
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
    depends_on:
      - tempo
      - loki
      - mimir

  tempo:
    image: grafana/tempo:2.5.0
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo/tempo.yaml
      - tempo-storage:/var/tempo
    ports:
      - "3200:3200"

  loki:
    image: grafana/loki:3.0.0
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro

  mimir:
    image: grafana/mimir:2.12.0
    command: ["-config.expand-env=true", "-config.file=/etc/mimir/mimir.yml"]
    volumes:
      - ./mimir.yml:/etc/mimir/mimir.yml
    ports:
      - "9009:9009"
      - "9180:9180"

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol-config.yaml"]
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - loki
      - tempo

volumes:
  tempo-storage:
